### PR TITLE
fix readme links, add taxonomy endpoint

### LINKED ISSUE #5: Add basic endpiont for taxonomy
Add a basic taxonomy endpoint.

### PR DESCRIPTION
**Pull request by mihiramin89**
Adds a basic endpoint to grab the data from https://ckan.smartcolumbusos.com/dataset/food-pantry-and-user-data/resource/371dd944-411c-4851-a065-9f3f605ddfb9

You can see the endpoint data from this endpoint http://localhost:8080/taxonomys.
 Fixes #5

### CODE REVIEW

**Review by vijayyadav06 — APPROVED** [review]

File: service.go [hunk 1]
```diff
@@ -1,40 +1,79 @@
...
-	VolunteerFlag      string
-	AddUser            string
-	AddDate            time.Time
-	SubCatID           int
-	DHSDescription     string
-	UpdateUser         string
-	UpdateDate         time.Time
+type Record struct {
+	ID                 int         `json:"_id"`
+	TAXONID            int         `json:"TAXON_ID"`
```
Comment (tsedgwick) [inline service.go:16]: Do we want to work with these fields in all caps throughout the code?  We can just make these camel case and have the json tag do the transformation - `json:"TAXON_ID"`

File: service.go [hunk 2]
```diff
@@ -1,40 +1,79 @@
...
-		{
-			ID:          1,
-			Description: "Test Provider",
-		},
-	}, nil
+type taxonomyService struct {
+}
+
+func (f taxonomyService) Taxonomy() ([]Record, error) {
+	resp, err := http.Get("https://ckan.smartcolumbusos.com/api/3/action/datastore_search?resource_id=371dd944-411c-4851-a065-9f3f605ddfb9")
```
Comment (tsedgwick) [inline service.go:58]: Next steps would be probably not fetching this on every click (caching, prefetching, maybe both)

Comment (tsedgwick) [reply service.go:58]: We should also have a test for this func.
